name: iOS Manual Full (1)

on:
  workflow_dispatch:
#  push:
#    branches: [master]

#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]

env:
  SHEME: Runner
  BUILD_CONFIGURATION: Release
  TEAM_ID: ZS99A4QXZW

jobs:
  build_ios:
    runs-on: macos-latest
    env:
      SHEME: Runner
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Install the provisioning profile
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}

        run: |
          # create variables
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

          # import provisioning profile from secrets
          echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'

      - name: Restore packages
        run: flutter pub get

      - name: Build Flutter
        run: flutter build ios --release --no-codesign

      - name: Upload Runner.app
        uses: actions/upload-artifact@v1
        with:
          name: ios-release-production-no-codesign-manual.app
          path: build/ios/iphoneos/Runner.app

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme ${{ env.SHEME }} -configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Build xArchive
        run: |
          xcodebuild \
          -workspace ios/Runner.xcworkspace \
          -scheme ${{ env.SHEME }} \
          -configuration ${{ env.BUILD_CONFIGURATION }} \
          DEVELOPMENT_TEAM=${{ env.TEAM_ID }} \
          -sdk 'iphoneos' \
          -destination 'generic/platform=iOS' \
          -archivePath build-output/app.xcarchive \
          PROVISIONING_PROFILE=fd964007-fc60-4afc-9b47-b98c3b81a7f9 \
          clean archive \
          CODE_SIGN_IDENTITY="Apple Development"

      - name: Export ipa
        run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist

      - name: Upload iOS Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: release-ios
          path: build-output/ios
